// hard coded version of the module registration functions. Will have to eventually be autogenerated

#include "modules.gen.h"

#if vex_renderer_ENABLED
#include <modules/vex_renderer/register_module.h>
#endif

namespace feather {

// Called once per level the engine enters; each module decides which levels it
// has anything to do at. Entering a level twice or out of order is caught in
// enter_init_level() (core/main/init_level.cpp), not here.
void register_modules(InitLevel level) {
#if vex_renderer_ENABLED
	register_vex_renderer(level);
#endif
}

void unregister_modules(InitLevel level) {
#if vex_renderer_ENABLED
	unregister_vex_renderer(level);
#endif
}

} //namespace feather
