set_xmakever("2.9.0")
set_project("feather")
set_version("1.0.0")
set_languages("cxx23")

-- ---- Options and helpers ------------------------------------------------
includes("xmake/options.lua")
includes("xmake/helper.lua")

-- ---- Build modes --------------------------------------------------------
-- debug      → CMake Debug       (-O0, symbols, BETA, no NDEBUG)
-- releasedbg → CMake Development (-O2, symbols, BETA, no NDEBUG)
-- release    → CMake Release     (-O3, NDEBUG)
add_rules("mode.debug", "mode.releasedbg", "mode.release")

-- Keep compile_commands.json up to date for clangd / clang-tidy
add_rules("plugin.compile_commands.autoupdate", {outputdir = "$(builddir)"})

-- ---- Global platform defines --------------------------------------------
if is_plat("windows") then
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
end
if is_plat("macosx") then
    add_cxflags("-fexperimental-library", {force = true})
end

-- ---- LTO ----------------------------------------------------------------
-- set_policy can be called at global scope; per-toolchain flags go in apply_compile_flags
if has_config("production") or has_config("use_lto") then
    set_policy("build.optimization.lto", true)
end

-- ---- Static C++ runtime on MSVC (set_runtimes must be global) -----------
-- is_toolchain() is unavailable here, so we set both MT/MTd via mode check;
-- the MSVC runtime is only relevant when actually using MSVC/clang-cl.
if has_config("production") or has_config("static_cpp") then
    set_runtimes(is_mode("debug") and "MTd" or "MT")
end

-- ---- Third-party packages and local targets -----------------------------
includes("thirdparty/xmake.lua")

-- ---- feather_public_api -------------------------------------------------
-- Headeronly umbrella target that gives modules engine include dirs and
-- PUBLIC thirdparty headers without creating a module→executable circular dep.
target("feather_public_api")
    set_kind("headeronly")
    add_includedirs("$(projectdir)", {public = true})
    add_includedirs("$(projectdir)/core", {public = true})
    -- SimpleMath headers: added directly because xmake doesn't reliably propagate
    -- public include dirs across a headeronly dep boundary (simplemath -> feather_public_api -> executables)
    add_includedirs("$(projectdir)/thirdparty/SimpleMath", {public = true})
    -- directxmath and simplemath are PUBLIC in CMake (their types appear in engine headers)
    add_packages("directxmath", {public = true})
    add_deps("simplemath", {public = true})
    -- flecs headers appear in core/world/ headers
    add_packages("flecs", {public = true})
    -- launch_settings.h (public) includes args.hxx, so modules need this too
    add_packages("taywee_args", {public = true})
    -- core/main/window.h includes <SDL3/SDL_events.h>, so any module that
    -- transitively includes engine headers needs SDL3's include path.
    add_packages("sdl3", {public = true})
target_end()

-- ---- Core source files --------------------------------------------------
-- Mirrors FEATHER_CORE_SOURCES in CMakeLists.txt exactly.
local CORE_SOURCES = {
    "core/framework/callable.cpp",
    "core/framework/reflected.cpp",
    "core/framework/shared_library.cpp",
    "core/framework/variant.cpp",
    "core/framework/variant_array.cpp",
    "core/main/class_db.cpp",
    "core/main/engine.cpp",
    "core/main/engine_settings.cpp",
    "core/main/feather_main.cpp",
    "core/main/launch_settings.cpp",
    "core/main/project_settings.cpp",
    "core/main/window.cpp",
    "core/main/simulation.cpp",
    "core/main/world_sim.cpp",
    "core/math/math_defs.cpp",
    "core/math/projection.cpp",
    "core/math/transform.cpp",
    "core/rendering/mesh_data.cpp",
    "core/rendering/renderer.cpp",
    "core/rendering/rendering_server.cpp",
    "core/rendering/render_scene.cpp",
    "core/resources/material.cpp",
    "core/resources/material_format_loader.cpp",
    "core/resources/mesh.cpp",
    "core/resources/mesh_format_loader.cpp",
    "core/resources/resource.cpp",
    "core/resources/resource_format_loader.cpp",
    "core/resources/resource_loader.cpp",
    "core/resources/rid.cpp",
    "core/resources/shader.cpp",
    "core/resources/texture.cpp",
    "core/resources/texture_format_loader.cpp",
    "core/resources/extension.cpp",
    "core/resources/extension_format_loader.cpp",
    "core/world/ecs_feature.cpp",
    "core/world/rendering_world_feature.cpp",
    "core/world/math_feature.cpp",
    "core/world/register_core_features.cpp",
    "core/world/core_world_feature.cpp",
    "core/world/components/scene.cpp",
}

local GENERATED_SOURCE = {
   -- Generated by tools/generate_core_registers.py (must exist before first compile)
    "core/framework/register_framework_types.gen.cpp",
    "core/main/register_main_types.gen.cpp",
    "core/math/register_math_types.gen.cpp",
    "core/rendering/register_rendering_types.gen.cpp",
    "core/resources/register_resources_types.gen.cpp",
    "core/world/register_world_types.gen.cpp",
    -- Generated embedded resources
    "raw_resources/resources.gen.cpp",
}

-- ---- Shared codegen function --------------------------------------------
-- Runs both Python code generation scripts before any source file compiles.
-- Python scripts use write_if_changed() internally, so re-runs are cheap.
local function run_codegen(target)
    local proj = os.projectdir()
    cprint("${cyan}[codegen]${reset} generate_core_registers.py")
    os.vrunv("python3", {
        path.join(proj, "tools", "generate_core_registers.py"),
        "--core-path", path.join(proj, "core"),
    }, {curdir = proj})
    cprint("${cyan}[codegen]${reset} generate_embedded_resources.py")
    os.vrunv("python3", {
        path.join(proj, "tools", "generate_embedded_resources.py"),
    }, {curdir = proj})
end

-- ---- Per-toolchain compile flags helper ---------------------------------
local function apply_compile_flags(target)
    local want_lto     = has_config("production") or has_config("use_lto")
    local want_static  = has_config("production") or has_config("static_cpp")

    -- Detect the compiler from the resolved target. is_toolchain() is a
    -- description-scope global and is nil inside on_config, so query the tool.
    local function is_msvc()  return target:has_tool("cxx", "cl", "clang_cl") end
    local function is_clang() return target:has_tool("cxx", "clang", "clangxx") end

    -- ThinLTO on non-MSVC
    if want_lto and not is_msvc() then
        target:add("cxflags", "-flto=thin", {force = true})
        target:add("ldflags", "-flto=thin", {force = true})
    end

    -- Static C++ runtime on Linux (clang uses libc++; skip it for non-GCC)
    if want_static and is_plat("linux") and not is_clang() then
        target:add("ldflags", "-static-libgcc", "-static-libstdc++", {force = true})
    end

    -- Sanitizers (debug + non-MSVC only)
    if has_config("enable_sanitizers") and is_mode("debug") and not is_msvc() then
        target:add("cxflags", "-fsanitize=address,undefined", "-fno-omit-frame-pointer", {force = true})
        target:add("ldflags", "-fsanitize=address,undefined", {force = true})
    end

    if is_msvc() then
        target:add("cxflags", "/W4", "/wd4100", {force = true})
        if is_mode("debug") then
            target:add("cxflags", "/Od", "/Zi", {force = true})
        elseif is_mode("releasedbg") then
            target:add("cxflags", "/O2", "/Zi", {force = true})
        elseif is_mode("release") then
            target:add("cxflags", "/O2", {force = true})
        end
    else
        target:add("cxflags",
            "-Wall", "-Wextra", "-pedantic", "-Wno-unused-parameter",
            {force = true})
        if is_mode("debug") then
            target:add("cxflags", "-g", "-O0", {force = true})
        elseif is_mode("releasedbg") then
            target:add("cxflags", "-g", "-O2", {force = true})
        elseif is_mode("release") then
            target:add("cxflags", "-O3", {force = true})
        end
    end
end

-- ---- Main executables ---------------------------------------------------
for _, variant in ipairs({"editor", "standalone"}) do
    target("feather." .. variant)
        set_kind("binary")
        set_basename("feather." .. variant)
        set_targetdir("$(builddir)/bin")
        add_files(CORE_SOURCES)
        add_files(GENERATED_SOURCE, {always_added=true})
        -- modules.gen.cpp is hand-authored (despite the .gen extension); include as regular source
        add_files("modules/modules.gen.cpp")
        add_includedirs("$(projectdir)", "$(projectdir)/core")

        -- EDITOR_BUILD define: PUBLIC on editor so module libs compiled into this exe see it.
        -- Matches CMake: Editor uses PUBLIC, Standalone uses PRIVATE.
        if variant == "editor" then
            add_defines("EDITOR_BUILD=1", {public = true})
        else
            add_defines("EDITOR_BUILD=0")
        end

        -- BETA in debug + releasedbg (CMake Development), absent in release
        if is_mode("debug", "releasedbg") then
            add_defines("BETA")
        end

        -- PRODUCTION for release builds (mirrors CMake option)
        if is_mode("release") then
            add_defines("PRODUCTION")
        end

        -- Third-party deps (private: consumers of the engine don't need these headers)
        add_deps("feather_public_api")
        add_packages("flecs", "assimp", "sdl3", "taywee_args")

        -- Code generation: run both Python scripts before compilation
        before_build(run_codegen)

        -- Copy shaders directory next to the executable after every build
        after_build(function(t)
            os.cp(
                path.join(os.projectdir(), "raw_resources", "shaders"),
                path.join(t:targetdir(), "shaders"))
        end)

        -- on_config, not on_load: toolchain-conditional flags (libc++/lld) need
        -- the resolved toolchain, which isn't available at load time.
        on_config(apply_compile_flags)

        -- Windows symbol export for runtime plugin/module loading.
        -- CMake used WINDOWS_EXPORT_ALL_SYMBOLS + ENABLE_EXPORTS on the executables.
        -- Phase 1: point at a pre-generated .def file extracted from the CMake build.
        --   1. Build once with CMake: cmake --preset multi && cmake --build --preset multi-development
        --   2. Extract: dumpbin /EXPORTS build\multi\bin\Development\feather.editor.exe
        --   3. Keep only the EXPORTS section, save as tools/feather.{variant}.def
        --   4. Uncomment the add_ldflags line below.
        -- Phase 2 (long-term): add FEATHER_API __declspec(dllexport/import) decorators.
        --
        -- if is_plat("windows") then
        --     add_ldflags(
        --         "/DEF:" .. path.join(os.projectdir(), "tools", "feather." .. variant .. ".def"),
        --         {force = true})
        -- end
    target_end()
end

-- ---- Modules (auto-discovered; re-opens feather.editor/standalone) ------
-- Must come after the executor targets are declared so feather_module_target()
-- can re-open them to add_deps().
includes("modules/xmake.lua")
