-- xmake/core_sources.lua: the engine's core source list, generated-source
-- list, and codegen/flags callbacks -- split out of xmake/engine.lua so a
-- static shipping build (plugin-abi-rework plan, Stage 7) can fold these
-- same sources directly into a consumer's own executable target
-- (feather_game_target(), tools/SDK/FeatherSDK.lua) instead of only ever
-- building the standalone "feather" target engine.lua itself defines.
--
-- includes()'d from BOTH engine.lua (dynamic mode: the engine's own dev/
-- editor feather.exe) and FeatherSDK.lua (static mode: a consumer's own
-- executable) -- xmake deduplicates includes() by absolute path within one
-- project run, so this only ever executes once per build regardless of how
-- many callers include it. Never included by both callers in the SAME
-- project run in practice: the engine repo's own build only ever pulls this
-- in via engine.lua, and a consumer's build only ever pulls it in via
-- FeatherSDK.lua -- two entirely separate xmake project graphs.
--
-- Rooted at os.scriptdir() rather than $(projectdir)/os.projectdir(), same
-- reasoning as every other file here that might be includes()'d cross-repo.
local FEATHER_ROOT = path.directory(os.scriptdir())

local function core_path(p) return path.join(FEATHER_ROOT, p) end

-- Mirrors FEATHER_CORE_SOURCES in the old CMakeLists.txt exactly.
CORE_SOURCES = {}
for _, p in ipairs({
    "core/framework/callable.cpp",
    "core/framework/reflected.cpp",
    "core/framework/shared_library.cpp",
    "core/framework/variant.cpp",
    "core/framework/variant_array.cpp",
    "core/main/class_db.cpp",
    "core/main/engine.cpp",
    "core/main/engine_settings.cpp",
    "core/main/feather_main.cpp",
    "core/main/launch_settings.cpp",
    "core/main/project_settings.cpp",
    "core/main/window.cpp",
    "core/main/simulation.cpp",
    "core/main/world_sim.cpp",
    "core/math/math_defs.cpp",
    "core/math/projection.cpp",
    "core/math/transform.cpp",
    "core/rendering/mesh_data.cpp",
    "core/rendering/renderer.cpp",
    "core/rendering/rendering_server.cpp",
    "core/rendering/render_scene.cpp",
    "core/resources/material.cpp",
    "core/resources/material_format_loader.cpp",
    "core/resources/mesh.cpp",
    "core/resources/mesh_format_loader.cpp",
    "core/resources/resource.cpp",
    "core/resources/resource_format_loader.cpp",
    "core/resources/resource_loader.cpp",
    "core/resources/rid.cpp",
    "core/resources/shader.cpp",
    "core/resources/texture.cpp",
    "core/resources/texture_format_loader.cpp",
    "core/resources/extension.cpp",
    "core/resources/extension_format_loader.cpp",
    "core/resources/extension_registry.cpp",
    "core/world/ecs_api.cpp",
    "core/world/ecs_feature.cpp",
    "core/world/rendering_world_feature.cpp",
    "core/world/math_feature.cpp",
    "core/world/register_core_features.cpp",
    "core/world/core_world_feature.cpp",
    "core/world/components/scene.cpp",
}) do
    table.insert(CORE_SOURCES, core_path(p))
end

GENERATED_SOURCE = {}
for _, p in ipairs({
   -- Generated by tools/codegen/generate_reflection.py (must exist before first compile)
    "core/framework/register_framework_types.gen.cpp",
    "core/main/register_main_types.gen.cpp",
    "core/math/register_math_types.gen.cpp",
    "core/rendering/register_rendering_types.gen.cpp",
    "core/resources/register_resources_types.gen.cpp",
    "core/world/register_world_types.gen.cpp",
    -- Embedded resources are header-only (raw_resources/*.gen.h), so no .cpp here.
}) do
    table.insert(GENERATED_SOURCE, core_path(p))
end

-- Runs both codegen scripts before any source file compiles; both use
-- write_if_changed() internally, so repeated runs are cheap. The actual
-- generate_reflection.py invocation lives in xmake/modules/feather_codegen.lua,
-- imported below, rather than as a plain function in this file: on_load/before_build/etc
-- scripts run inside a sandbox with its own _ENV that doesn't see ordinary Lua
-- globals defined at xmake.lua description scope, only xmake's own APIs and
-- import()ed modules -- and modules/vex_renderer/xmake.lua's own before_build
-- hook needs this same logic (see feather_codegen.run_module_codegen and the
-- comment there for why).
--
-- FEATHER_ROOT (the upvalue captured above), not os.projectdir(), is threaded
-- through as opts.feather_root: feather_codegen.lua's own functions default
-- that to os.projectdir(), which is wrong the moment this file is includes()'d
-- from a consumer's build.
function run_core_source_codegen(target)
    import("feather_codegen")

    -- Modules using FCLASS live outside core/ and need their own --module-path so
    -- the generator scans them too (see process_source_dir() in
    -- generate_reflection.py). This pass is redundant with vex_renderer's own
    -- before_build hook (feather_codegen.run_module_codegen) -- that one exists
    -- for build-ordering correctness, this one keeps `xmake` alone (without a full
    -- rebuild) sufficient to refresh everything. vex_renderer is skipped entirely
    -- on macOS (see modules/vex_renderer/xmake.lua) and gated by enable_vex_renderer
    -- elsewhere, so mirror both checks here rather than feeding the generator a
    -- directory whose FCLASS headers aren't actually being compiled into this build.
    local module_dirs = {}
    if not is_plat("macosx") and has_config("enable_vex_renderer") then
        local vex_dir = path.join(FEATHER_ROOT, "modules", "vex_renderer")
        if os.isdir(vex_dir) then
            table.insert(module_dirs, vex_dir)
        end
    end
    feather_codegen.run_core_codegen(module_dirs, {feather_root = FEATHER_ROOT})

    cprint("${cyan}[codegen]${reset} generate_embedded_resources.py")
    os.vrunv("python3", {
        path.join(FEATHER_ROOT, "tools", "codegen", "generate_embedded_resources.py"),
    }, {curdir = FEATHER_ROOT})
end

-- Body lives in xmake/modules/feather_flags.lua so tools/SDK/FeatherSDK.lua can
-- import() the exact same flags for downstream project DLLs -- notably
-- -Wno-attributes, which reflection's bare [[get]]/[[method]] attributes need
-- wherever an FCLASS header is compiled.
function apply_core_compile_flags(target)
    import("feather_flags")
    feather_flags.apply(target)
end
