-- Engine target declarations, kept out of root xmake.lua so this file can be
-- includes()'d cross-repo without dragging in set_project()/set_version().
-- Thirdparty packages and feather_public_api must be includes()'d first.
--
-- os.scriptdir(), not os.projectdir(): the latter would resolve to a
-- CONSUMER's repo if this file were ever includes()'d cross-repo.
local FEATHER_ROOT = path.directory(os.scriptdir())

-- ---- Core source files ----------------------------------------------------
-- add_files() resolves relative paths against this file's own directory, not the engine root, so every entry joins FEATHER_ROOT explicitly.
local function core_path(p) return path.join(FEATHER_ROOT, p) end

local CORE_SOURCES = {}
for _, p in ipairs({
    "core/framework/alloc.cpp",
    "core/framework/callable.cpp",
    "core/framework/reflected.cpp",
    "core/framework/shared_library.cpp",
    "core/framework/variant.cpp",
    "core/framework/variant_array.cpp",
    "core/main/class_db.cpp",
    "core/main/engine.cpp",
    "core/main/engine_settings.cpp",
    "core/main/feather_main.cpp",
    "core/main/init_level.cpp",
    "core/main/launch_settings.cpp",
    "core/main/project_settings.cpp",
    "core/main/window.cpp",
    "core/main/simulation.cpp",
    "core/main/world_sim.cpp",
    "core/math/math_defs.cpp",
    "core/math/math_types.cpp",
    "core/math/projection.cpp",
    "core/math/transform.cpp",
    "core/rendering/mesh_data.cpp",
    "core/rendering/renderer.cpp",
    "core/rendering/rendering_server.cpp",
    "core/rendering/render_scene.cpp",
    "core/resources/material.cpp",
    "core/resources/material_format_loader.cpp",
    "core/resources/mesh.cpp",
    "core/resources/mesh_format_loader.cpp",
    "core/resources/resource.cpp",
    "core/resources/resource_format_loader.cpp",
    "core/resources/resource_loader.cpp",
    "core/resources/rid.cpp",
    "core/resources/shader.cpp",
    "core/resources/texture.cpp",
    "core/resources/texture_format_loader.cpp",
    "core/resources/extension.cpp",
    "core/resources/extension_loading.cpp",
    "core/resources/fext_format_loader.cpp",
    "core/world/ecs_module.cpp",
    "core/world/world.cpp",
    "core/world/rendering_world_module.cpp",
    "core/world/math_module.cpp",
    "core/world/core_world_module.cpp",
    "core/world/scripted_component.cpp",
    "core/world/scripted_system.cpp",
    "core/world/components/scene.cpp",
}) do
    table.insert(CORE_SOURCES, core_path(p))
end

local GENERATED_SOURCE = {}
for _, p in ipairs({
   -- Generated by tools/codegen/generate_reflection.py (must exist before first compile)
    "core/framework/register_framework_types.gen.cpp",
    "core/main/register_main_types.gen.cpp",
    "core/math/register_math_types.gen.cpp",
    "core/rendering/register_rendering_types.gen.cpp",
    "core/resources/register_resources_types.gen.cpp",
    "core/world/register_world_types.gen.cpp",
    -- Embedded resources are header-only (raw_resources/*.gen.h), so no .cpp here.
}) do
    table.insert(GENERATED_SOURCE, core_path(p))
end

local function run_codegen(target)
    import("feather_codegen")

    local module_dirs = {}
    if not is_plat("macosx") and has_config("enable_vex_renderer") then
        local vex_dir = path.join(FEATHER_ROOT, "modules", "vex_renderer")
        if os.isdir(vex_dir) then
            table.insert(module_dirs, vex_dir)
        end
    end
    feather_codegen.run_core_codegen(module_dirs, {feather_root = FEATHER_ROOT})

    cprint("${cyan}[codegen]${reset} generate_embedded_resources.py")
    os.vrunv("python3", {
        path.join(FEATHER_ROOT, "tools", "codegen", "generate_embedded_resources.py"),
    }, {curdir = FEATHER_ROOT})
end

local function apply_compile_flags(target)
    import("feather_flags")
    feather_flags.apply(target)
end

-- ---- Main executable ------------------------------------------------------
target("feather")
    set_kind("binary")
    set_basename("feather")
    set_targetdir("$(builddir)/bin")
    add_files(CORE_SOURCES)
    add_files(GENERATED_SOURCE, {always_added=true})

    add_files(path.join(FEATHER_ROOT, "modules", "modules.gen.cpp"))
    add_includedirs(FEATHER_ROOT, path.join(FEATHER_ROOT, "core"))

    if is_mode("debug", "releasedbg") then
        add_defines("BETA")
    end
    if is_mode("release") then
        add_defines("PRODUCTION")
    end

    add_deps("feather_public_api")
    -- Direct, not just via feather_public_api (see public_api.lua): an
    -- object-kind dep's .o files don't propagate across a second headeronly hop.
    add_deps("simplemath")
    add_packages("flecs", "assimp", "sdl3", "taywee_args", "nlohmann_json")

    if is_plat("linux") then
        add_rpathdirs("$ORIGIN/lib", "$ORIGIN/runtime")
        -- Exports the engine's own symbols to what it dlopens: the generated C
        -- bindings a plugin calls, and sdl3's copy (xmake/public_api.lua).
        add_ldflags("-rdynamic", {force = true})
    end

    if is_plat("windows", "mingw") then
        -- project_settings.cpp calls SHGetFolderPathA directly; was only
        -- linking via sdl3's syslinks list, which broke once sdl3 went shared.
        add_syslinks("shell32")
    end

    if is_plat("mingw") then
        add_syslinks("stdc++exp")

        add_ldflags("-static-libgcc", "-static-libstdc++",
            "-Wl,-Bstatic,--whole-archive", "-lwinpthread", "-Wl,--no-whole-archive,-Bdynamic",
            -- GNU ld needs --out-implib explicitly (link.exe does this automatically).
            "-Wl,--out-implib,$(builddir)/bin/libfeather.a",
            {force = true})
    end

    before_build(run_codegen)

    add_rules("feather.deploy_shaders")
    add_rules("feather.deploy_shared_deps")
    
    on_config(apply_compile_flags)
target_end()

-- ---- Modules (auto-discovered; re-opens the feather target) -------------
-- Must come after the executable target so feather_module_target() can re-open it.
includes(path.join(FEATHER_ROOT, "modules", "xmake.lua"))
