-- xmake/engine.lua: engine target declarations (the feather executable, its
-- core sources, codegen wiring, and modules) -- kept out of the root
-- xmake.lua so it can eventually be includes()'d cross-repo -- e.g. by a
-- consumer building a fully static shipping executable (see
-- tools/SDK/FeatherSDK.lua) -- without dragging in set_project()/set_version()/
-- etc, which only make sense once, at the true top level. Thirdparty
-- packages and feather_public_api still need to be includes()'d by the
-- caller first; this file only owns the target declarations.
--
-- Rooted at os.scriptdir() rather than $(projectdir)/os.projectdir(), same
-- reasoning as xmake/public_api.lua: those resolve to whichever project is
-- top-level for the current invocation, which would be a CONSUMER's repo if
-- this file were ever includes()'d cross-repo. FEATHER_ROOT is captured once
-- here as a description-scope local and closed over by every callback below
-- (before_build/on_config).
local FEATHER_ROOT = path.directory(os.scriptdir())

-- ---- Core source files ----------------------------------------------------
-- Mirrors FEATHER_CORE_SOURCES in the old CMakeLists.txt exactly. add_files()
-- resolves a relative path against the CALLING script's own directory (this
-- file's, i.e. xmake/) -- not the engine root -- so every entry is joined
-- with FEATHER_ROOT explicitly rather than left bare.
local function core_path(p) return path.join(FEATHER_ROOT, p) end

local CORE_SOURCES = {}
for _, p in ipairs({
    "core/framework/callable.cpp",
    "core/framework/reflected.cpp",
    "core/framework/shared_library.cpp",
    "core/framework/variant.cpp",
    "core/framework/variant_array.cpp",
    "core/main/class_db.cpp",
    "core/main/engine.cpp",
    "core/main/engine_settings.cpp",
    "core/main/feather_main.cpp",
    "core/main/launch_settings.cpp",
    "core/main/project_settings.cpp",
    "core/main/window.cpp",
    "core/main/simulation.cpp",
    "core/main/world_sim.cpp",
    "core/math/math_defs.cpp",
    "core/math/projection.cpp",
    "core/math/transform.cpp",
    "core/rendering/mesh_data.cpp",
    "core/rendering/renderer.cpp",
    "core/rendering/rendering_server.cpp",
    "core/rendering/render_scene.cpp",
    "core/resources/material.cpp",
    "core/resources/material_format_loader.cpp",
    "core/resources/mesh.cpp",
    "core/resources/mesh_format_loader.cpp",
    "core/resources/resource.cpp",
    "core/resources/resource_format_loader.cpp",
    "core/resources/resource_loader.cpp",
    "core/resources/rid.cpp",
    "core/resources/shader.cpp",
    "core/resources/texture.cpp",
    "core/resources/texture_format_loader.cpp",
    "core/resources/extension.cpp",
    "core/resources/extension_format_loader.cpp",
    "core/extension/feather_interface.cpp",
    "core/extension/bridges/resource_format_loader_bridge.cpp",
    "core/world/ecs_feature.cpp",
    "core/world/rendering_world_feature.cpp",
    "core/world/math_feature.cpp",
    "core/world/register_core_features.cpp",
    "core/world/core_world_feature.cpp",
    "core/world/components/scene.cpp",
}) do
    table.insert(CORE_SOURCES, core_path(p))
end

local GENERATED_SOURCE = {}
for _, p in ipairs({
   -- Generated by tools/codegen/generate_reflection.py (must exist before first compile)
    "core/framework/register_framework_types.gen.cpp",
    "core/main/register_main_types.gen.cpp",
    "core/math/register_math_types.gen.cpp",
    "core/rendering/register_rendering_types.gen.cpp",
    "core/resources/register_resources_types.gen.cpp",
    "core/world/register_world_types.gen.cpp",
    -- Embedded resources are header-only (raw_resources/*.gen.h), so no .cpp here.
}) do
    table.insert(GENERATED_SOURCE, core_path(p))
end

-- Runs both codegen scripts before any source file compiles; both use
-- write_if_changed() internally, so repeated runs are cheap. The actual
-- generate_reflection.py invocation lives in xmake/modules/feather_codegen.lua,
-- imported below, rather than as a plain function in this file: on_load/before_build/etc
-- scripts run inside a sandbox with its own _ENV that doesn't see ordinary Lua
-- globals defined at xmake.lua description scope, only xmake's own APIs and
-- import()ed modules -- and modules/vex_renderer/xmake.lua's own before_build
-- hook needs this same logic (see feather_codegen.run_module_codegen and the
-- comment there for why).
--
-- FEATHER_ROOT (the upvalue captured above), not os.projectdir(), is threaded
-- through as opts.feather_root: feather_codegen.lua's own functions default
-- that to os.projectdir(), which is wrong the moment this file is includes()'d
-- from a consumer's build.
local function run_codegen(target)
    import("feather_codegen")

    -- Modules using FCLASS live outside core/ and need their own --module-path so
    -- the generator scans them too (see process_source_dir() in
    -- generate_reflection.py). This pass is redundant with vex_renderer's own
    -- before_build hook (feather_codegen.run_module_codegen) -- that one exists
    -- for build-ordering correctness, this one keeps `xmake` alone (without a full
    -- rebuild) sufficient to refresh everything. vex_renderer is skipped entirely
    -- on macOS (see modules/vex_renderer/xmake.lua) and gated by enable_vex_renderer
    -- elsewhere, so mirror both checks here rather than feeding the generator a
    -- directory whose FCLASS headers aren't actually being compiled into this build.
    local module_dirs = {}
    if not is_plat("macosx") and has_config("enable_vex_renderer") then
        local vex_dir = path.join(FEATHER_ROOT, "modules", "vex_renderer")
        if os.isdir(vex_dir) then
            table.insert(module_dirs, vex_dir)
        end
    end
    feather_codegen.run_core_codegen(module_dirs, {feather_root = FEATHER_ROOT})

    cprint("${cyan}[codegen]${reset} generate_embedded_resources.py")
    os.vrunv("python3", {
        path.join(FEATHER_ROOT, "tools", "codegen", "generate_embedded_resources.py"),
    }, {curdir = FEATHER_ROOT})
end

-- Body lives in xmake/modules/feather_flags.lua so tools/SDK/FeatherSDK.lua can
-- import() the exact same flags for downstream project DLLs -- notably
-- -Wno-attributes, which reflection's bare [[get]]/[[method]] attributes need
-- wherever an FCLASS header is compiled.
local function apply_compile_flags(target)
    import("feather_flags")
    feather_flags.apply(target)
end

-- ---- Main executable ------------------------------------------------------
-- EDITOR_BUILD comes from feather_public_api (xmake/public_api.lua), driven
-- by xmake/options.lua's editor_build option. Flip it with
-- `xmake f --editor_build=n && xmake build -r`.
target("feather")
    set_kind("binary")
    set_basename("feather")
    set_targetdir("$(builddir)/bin")
    add_files(CORE_SOURCES)
    add_files(GENERATED_SOURCE, {always_added=true})

    add_files(path.join(FEATHER_ROOT, "modules", "modules.gen.cpp"))
    add_includedirs(FEATHER_ROOT, path.join(FEATHER_ROOT, "core"))

    -- BETA in debug + releasedbg (CMake Development), absent in release
    if is_mode("debug", "releasedbg") then
        add_defines("BETA")
    end
    if is_mode("release") then
        add_defines("PRODUCTION")
    end

    add_deps("feather_public_api")
    add_packages("flecs", "assimp", "sdl3", "taywee_args")

    if is_plat("linux") then
        add_rpathdirs("$ORIGIN/lib", "$ORIGIN/runtime")
        -- Lets a dlopen'd project DLL resolve engine symbols at runtime.
        add_ldflags("-rdynamic", {force = true})
    end

    -- Windows analog: needs a .def file (dumpbin /EXPORTS) to get a companion
    -- import .lib. Not yet committed -- no-op until it exists.
    if is_plat("windows") then
        local def_file = path.join(FEATHER_ROOT, "tools", "feather.def")
        if os.isfile(def_file) then
            add_ldflags("/DEF:" .. def_file, {force = true})
        end
    end

    before_build(run_codegen)

    -- Copy raw_resources/shaders next to the executable after every build.
    add_rules("feather.deploy_shaders")

    -- on_config, not on_load: toolchain-conditional flags need the
    -- resolved toolchain, which isn't available at load time.
    on_config(apply_compile_flags)
target_end()

-- ---- Modules (auto-discovered; re-opens the feather target) -------------
-- Must come after the executable target so feather_module_target() can
-- re-open it to add_deps().
includes(path.join(FEATHER_ROOT, "modules", "xmake.lua"))
