-- xmake/modules/feather_static_registry.lua: generates the two small files
-- a static shipping build (plugin-abi-rework plan, Stage 7) needs and the
-- dynamic path doesn't -- static_extensions.gen.cpp (a POD table of every
-- linked-in plugin's feather_extension_<ident> function pointer, no static
-- initializers) and static_main.gen.cpp (a thin main() handing that table
-- to feather::feather_main()). See feather_game_target(),
-- tools/SDK/FeatherSDK.lua.
--
-- Plain Lua string generation, not a Python script like
-- generate_reflection.py: the extension set (which idents are statically
-- linked into THIS build) is a build-graph fact xmake's own target
-- configuration already knows, not something that needs source-scanning.
--
-- Must be a proper import()-able module, not a plain function in
-- FeatherSDK.lua, for the same reason feather_codegen.lua and
-- feather_flags.lua are: it's called from a before_build sandboxed
-- callback, which can't see description-scope Lua globals.

local function _write_if_changed(filepath, content)
    if os.isfile(filepath) then
        local existing = io.readfile(filepath)
        if existing == content then
            return
        end
    end
    io.writefile(filepath, content)
end

-- generate(project_root, idents)
--
-- idents: the ident(s) passed to this project's own FEATHER_DEFINE_EXTENSION
-- call(s) -- one feather_extension_<ident>() per statically linked plugin.
function generate(project_root, idents)
    local extern_decls = {}
    local table_entries = {}
    for _, ident in ipairs(idents) do
        table.insert(extern_decls, string.format('extern "C" const FeatherExtensionDesc* feather_extension_%s();', ident))
        table.insert(table_entries, string.format("\tfeather_extension_%s,", ident))
    end

    local extensions_content = string.format([[
// AUTO-GENERATED by xmake/modules/feather_static_registry.lua -- DO NOT EDIT.
// Re-run xmake to refresh.
#include <resources/extension_abi.h>

#include <cstddef>

%s

// A plain array of function pointers is a POD constant -- taking a
// function's address is a constant expression, calling it isn't -- so this
// needs no static initializers, consistent with the engine's own
// "registration is explicit calls" property (see the plugin-abi-rework
// plan's Stage 6/7) that's what makes static linking work without
// --whole-archive in the first place.
extern "C" const FeatherExtensionFn g_feather_static_extensions[] = {
%s
};
extern "C" const size_t g_feather_static_extension_count = %d;
]], table.concat(extern_decls, "\n"), table.concat(table_entries, "\n"), #idents)

    local main_content = [[
// AUTO-GENERATED by xmake/modules/feather_static_registry.lua -- DO NOT EDIT.
// Re-run xmake to refresh.
#include <main/feather_main.h>

extern "C" const FeatherExtensionFn g_feather_static_extensions[];
extern "C" const size_t g_feather_static_extension_count;

int main(int argc, char* argv[]) {
	return feather::feather_main(argc, argv, g_feather_static_extensions, g_feather_static_extension_count);
}
]]

    local extensions_path = path.join(project_root, "static_extensions.gen.cpp")
    local main_path = path.join(project_root, "static_main.gen.cpp")
    _write_if_changed(extensions_path, extensions_content)
    _write_if_changed(main_path, main_content)
end
