#!/usr/bin/env python3
"""
Generate self-contained C++ header files that embed the contents of every file
under raw_resources/ directly as a byte array.

Each source file gets a sibling `<name>.gen.h` containing:

    inline constexpr unsigned char <var>[]   -- the raw bytes, null-terminated
    inline constexpr std::size_t  <var>_size  -- byte count (excluding the
                                                 trailing null terminator)

The bytes are pulled in at compile time with the C++26 `#embed` directive, so no
separate translation unit / extern definition is needed. The trailing null lets
the data be used directly as a C string (e.g. shader source) via
`reinterpret_cast<const char*>(<var>)`.
"""

import argparse
import os
import sys
from pathlib import Path


def sanitize_variable_name(path: Path, base_path: Path) -> str:
    """
    Convert a file path to a valid C++ variable name.
    Example: raw_resources/shaders/pbr_forward.slang -> shaders_pbr_forward_slang
    """
    rel_path = path.relative_to(base_path)
    name = str(rel_path).replace(os.sep, '_').replace('/', '_').replace('.', '_')
    name = name.lstrip('_')
    return name


def generate_header(source_file: Path, output_file: Path, base_path: Path, dry_run: bool = False) -> str:
    """
    Generate a self-contained header embedding the bytes of `source_file`.
    Returns the variable name used.
    """
    var_name = sanitize_variable_name(source_file, base_path)
    rel_display = source_file.relative_to(base_path).as_posix()

    # The header lives next to its source file, so #embed can reference the
    # source by its bare filename (resolved relative to the header's directory,
    # exactly like #include "...").
    embed_name = source_file.name

    header_content = f"""#pragma once
// Auto-generated by tools/generate_embedded_resources.py -- do not edit.
// Embedded contents of raw_resources/{rel_display}
#include <cstddef>

inline constexpr unsigned char {var_name}[] = {{
#embed "{embed_name}" suffix(,)
    0 // null terminator so the data is usable as a C string
}};

// Byte count of the embedded resource, excluding the trailing null terminator.
inline constexpr std::size_t {var_name}_size = sizeof({var_name}) - 1;
"""

    if dry_run:
        print(f"[dry-run] Would generate header: {output_file}")
        return var_name

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header_content)

    print(f"Generated header: {output_file}")
    return var_name


def clean_generated(raw_resources_dir: Path, project_root: Path, dry_run: bool = False) -> None:
    """Remove all generated .gen.h files (and any stale resources.gen.cpp)."""
    removed_count = 0

    for gen_file in sorted(raw_resources_dir.rglob('*.gen.h')):
        if dry_run:
            print(f"[dry-run] Would remove: {gen_file}")
        else:
            gen_file.unlink()
            print(f"Removed: {gen_file}")
        removed_count += 1

    # Clean up the legacy single-cpp artifact if it is still lying around.
    legacy_cpp = raw_resources_dir / 'resources.gen.cpp'
    if legacy_cpp.exists():
        if dry_run:
            print(f"[dry-run] Would remove: {legacy_cpp}")
        else:
            legacy_cpp.unlink()
            print(f"Removed: {legacy_cpp}")
        removed_count += 1

    print()
    print("Summary:")
    if dry_run:
        print(f"  Would remove: {removed_count} file(s)")
    else:
        print(f"  Removed: {removed_count} file(s)")


def should_process_file(file_path: Path) -> bool:
    """
    Determine if a file should have a header generated for it.
    Skips generated headers, C/C++ sources and other build artifacts.
    """
    if file_path.suffix in ['.h', '.hpp', '.hxx', '.cpp', '.cxx', '.cc']:
        return False
    if file_path.name.startswith('.'):
        return False
    skip_extensions = ['.o', '.obj', '.exe', '.dll', '.so', '.dylib', '.a', '.lib']
    if file_path.suffix.lower() in skip_extensions:
        return False
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Generate self-contained C++ headers embedding every file "
                    "under raw_resources as a null-terminated byte array."
    )
    parser.add_argument(
        '--dry-run', action='store_true',
        help="Print what would be done without writing or deleting any files."
    )
    parser.add_argument(
        '--clean', action='store_true',
        help="Remove all generated .gen.h files."
    )
    parser.add_argument(
        '--force', action='store_true',
        help="Overwrite existing generated files instead of skipping them."
    )
    args = parser.parse_args()

    script_dir = Path(__file__).parent.resolve()
    project_root = script_dir.parent
    raw_resources_dir = project_root / 'raw_resources'

    if not raw_resources_dir.exists():
        print(f"Error: raw_resources directory not found at {raw_resources_dir}", file=sys.stderr)
        sys.exit(1)

    if args.clean:
        print(f"Cleaning generated files under: {raw_resources_dir}")
        if args.dry_run:
            print("[dry-run mode]")
        print()
        clean_generated(raw_resources_dir, project_root, dry_run=args.dry_run)
        return

    print(f"Scanning: {raw_resources_dir}")
    print(f"Project root: {project_root}")
    if args.dry_run:
        print("[dry-run mode]")
    elif args.force:
        print("[force mode - overwriting existing files]")
    print()

    generated_count = 0
    skipped_count = 0

    for source_file in sorted(raw_resources_dir.rglob('*')):
        if source_file.is_dir():
            continue
        if not should_process_file(source_file):
            skipped_count += 1
            continue

        output_file = source_file.parent / f"{source_file.name}.gen.h"

        if not args.force and not args.dry_run and output_file.exists():
            # Regenerate when the source is newer than its generated header so
            # edits to resources are picked up without a manual --force.
            if output_file.stat().st_mtime >= source_file.stat().st_mtime:
                skipped_count += 1
                continue

        try:
            generate_header(source_file, output_file, raw_resources_dir, dry_run=args.dry_run)
            generated_count += 1
        except Exception as e:
            print(f"Error generating header for {source_file}: {e}", file=sys.stderr)
            continue

    print()
    print("Summary:")
    if args.dry_run:
        print(f"  Would generate: {generated_count} header(s)")
    else:
        print(f"  Generated: {generated_count} header(s)")
    print(f"  Skipped: {skipped_count} file(s)")


if __name__ == '__main__':
    main()