#main feather engine build file

# package(
#     name = "feather engine",
#     allow_empty = true,
# )

cc_binary(
    name = "feather",
    srcs = glob([
        "core/*.cpp",
        "core/*.h*",
    ]),
    includes = ["."],
)
